function zobrazreklamu2() 
{
var i=Math.round(Math.random()*2);

if (i==0) text='<div class="row reklama1" dir="rtl"><div class="gadhe"><p class="h1_text"><a href="https://www.smartlation.com/?utm_source=direct&utm_campaign=prekladacreklama" target="_blank" title="הזמנת תרגום מקצועי">הזמנת תרגום מקצועי</a></p><p class="p_text"><a href="https://www.smartlation.com/?utm_source=direct&utm_campaign=prekladacreklama" target="_blank" title="הזמנת תרגום מקצועי"><img src="/img/certifications.png" class="imgreklama1 floatright" alt="הזמנת תרגום מקצועי"></a><a href="https://www.smartlation.com/?utm_source=direct&utm_campaign=prekladacreklama" target="_blank" title="שירותי תרגום מקצועיים 24/7 שוק המתרגמים - תרגום מסמכים תרגום מקצועי Smartlation.com אנחנו לא סוכנות תרגום - אנחנו פלטפורמה המחברת בין מתרגמים ולקוחות ברחבי העולם">שירותי תרגום מקצועיים 24/7 שוק המתרגמים - תרגום מסמכים תרגום מקצועי Smartlation.com אנחנו לא סוכנות תרגום - אנחנו פלטפורמה המחברת בין מתרגמים ולקוחות ברחבי העולם</a></p><p class="link_text"><a href="https://www.smartlation.com/?utm_source=direct&utm_campaign=prekladacreklama" target="_blank" title="Smartlation">www.smartlation.com</a></p><a href="https://www.smartlation.com/?utm_source=direct&utm_campaign=prekladacreklama" target="_blank" class="gad_linkhe"></a></div><br><div class="w3-left w3-padding"><small class="breeserif glyphicon pointerrefresh24" onclick="zobrazreklamu2();" title="תרגום מקוון חינם - רענון">תרגום מקוון חינם - פרסומת &#xe031;</small></div></div>'; 
	
if (i==1) text='<div class="row reklama1" dir="rtl"><div class="gadhe"><p class="h1_text"><a href="https://www.smartlationpro.com/?affiliate=prekladac&utm_source=peter&utm_campaign=prekladacreklama" target="_blank" title="למצוא מתרגם מקצועי עבור חברת תרגום שלך">למצוא מתרגם מקצועי עבור חברת תרגום שלך</a></p><p class="p_text"><a href="https://www.smartlationpro.com/?affiliate=prekladac&utm_source=peter&utm_campaign=prekladacreklama" target="_blank" title="למצוא מתרגם מקצועי עבור חברת תרגום שלך"><img src="/img/5medium.jpg" class="imgreklama1 floatright"></a><a href="https://www.smartlationpro.com/?affiliate=prekladac&utm_source=peter&utm_campaign=prekladacreklama" target="_blank" title="מתרגם מקצועי - מרקטפלייס של - שירותי תרגום 24/7  | Smartlationpro.com | זה לא חברת תרגום - זה פאטפורמה של אלפי מתרגמים מרחבי העולם">מרקטפלייס של - שירותי תרגום 24/7  | Smartlationpro.com | זה לא חברת תרגום - זה פאטפורמה של אלפי מתרגמים מרחבי העולם</a></p><p class="link_text"><a href="https://www.smartlationpro.com/?affiliate=prekladac&utm_source=peter&utm_campaign=prekladacreklama" target="_blank" title="Smartlationpro">www.smartlationpro.com</a></p><a href="https://www.smartlationpro.com/?affiliate=prekladac&utm_source=peter&utm_campaign=prekladacreklama" target="_blank" class="gad_linkhe"></a></div><br><div class="w3-left w3-padding"><small class="breeserif glyphicon pointerrefresh24" onclick="zobrazreklamu2();" title="תרגום מקוון חינם - רענון">תרגום מקוון חינם - פרסומת &#xe031;</small></div></div>'; 
	
if (i==2) text='<div class="row reklama1" dir="rtl"><div class="gadhe"><p class="h1_text"><a href="https://www.smartlationpro.com/translators/?utm_source=direct&utm_campaign=prekladacreklama" target="_blank" title="עבודה למתרגם">עבודה למתרגם</a></p><p class="p_text"><a href="https://www.smartlationpro.com/translators/?utm_source=direct&utm_campaign=prekladacreklama" target="_blank" title="עבודה למתרגם"><img src="/img/6medium.jpg" class="imgreklama1 floatright" alt="עבודה למתרגם"></a><a href="https://www.smartlationpro.com/translators/?utm_source=direct&utm_campaign=prekladacreklama" target="_blank" title="מרקטפלייס - 24/7 הרשמת המתרגם Smartlationpro.com אנו מחברים בין מתרגמים ולקוחות ברחבי העולם">מרקטפלייס - 24/7 הרשמת המתרגם Smartlationpro.com אנו מחברים בין מתרגמים ולקוחות ברחבי העולם</a></p><p class="link_text"><a href="https://www.smartlationpro.com/translators/?utm_source=direct&utm_campaign=prekladacreklama" target="_blank" title="Smartlationpro">www.smartlationpro.com</a></p><a href="https://www.smartlationpro.com/translators/?utm_source=direct&utm_campaign=prekladacreklama" target="_blank" class="gad_linkhe"></a></div><br><div class="w3-left w3-padding"><small class="breeserif glyphicon pointerrefresh24" onclick="zobrazreklamu2();" title="תרגום מקוון חינם - רענון">תרגום מקוון חינם - פרסומת &#xe031;</small></div></div>'; 

var vse = '<section id="reklama2" title="פרסומת" class="margin5 anton">' + text + '</section>'; 

document.getElementById('ads2').innerHTML = vse;
} 
zobrazreklamu2();