function zobrazreklamupopup() 
{
var i=Math.round(Math.random()*4); 

if (i==0) text='<div class="row reklama1"><div class="gad"><p class="h1_text"><a href="https://www.smartlation.com/?utm_source=direct&utm_campaign=prekladacreklama" target="_blank" title="Objednat profesionální překlad">Objednat profesionální překlad</a></p><p class="p_text"><a href="https://www.smartlation.com/?utm_source=direct&utm_campaign=prekladacreklama" target="_blank" title="Objednat profesinální překlad"><img src="/img/certifications.png" class="imgreklama1 floatleft" alt="Objednat profesionální překlad"></a><a href="https://www.smartlation.com/?utm_source=direct&utm_campaign=prekladacreklama" target="_blank" title="Profesionální překladatelské služby 24/7 | Překladatelský Marketplace-  Překlad dokumentů | Odborné překlady | Smartlation.com | Nejsme překladatelská agentura - jsme platforma spojující překladatele a zákazníky celého světa">Profesionální překladatelské služby 24/7 | Překladatelský Marketplace-  Překlad dokumentů | Odborné překlady | Smartlation.com | Nejsme překladatelská agentura - jsme platforma spojující překladatele a zákazníky celého světa</a></p><p class="link_text"><a href="https://www.smartlation.com/?utm_source=direct&utm_campaign=prekladacreklama" target="_blank" title="Smartlation">www.smartlation.com</a></p><a href="https://www.smartlation.com/?utm_source=direct&utm_campaign=prekladacreklama" target="_blank" class="gad_link"></a></div></div>'; 
	
if (i==1) text='<div class="row reklama1"><div class="gad"><p class="h1_text"><a href="https://www.profesionalnipreklady.cz/?utm_source=direct&utm_campaign=prekladacreklama" target="_blank" title="Profesionální překlady">Profesionální překlady</a></p><p class="p_text"><a href="https://www.profesionalnipreklady.cz/?utm_source=direct&utm_campaign=prekladacreklama" target="_blank" title="Profesionální překlady"><img src="/img/3small.jpg" class="imgreklama1 floatleft" alt="Profesionální překlady"></a><a href="https://www.profesionalnipreklady.cz/?utm_source=direct&utm_campaign=prekladacreklama" target="_blank" title="Nepřetržité překladatelské služby 24/7 | Agentura-  Překlad dokumentů | Soudní překlady | Odborné překlady | Okamžitá cenová nabídka | profesionalnipreklady.cz | První česká překladatelská agentura s technologí od Smartlation">Nepřetržité překladatelské služby 24/7 | Agentura-  Překlad dokumentů | Soudní překlady | Odborné překlady | Okamžitá cenová nabídka | profesionalnipreklady.cz | První česká překladatelská agentura s technologí od Smartlation</a></p><p class="link_text"><a href="https://www.profesionalnipreklady.cz/?utm_source=direct&utm_campaign=prekladacreklama" target="_blank" title="Profesionální překlady">www.profesionalnipreklady.cz</a></p><a href="https://www.profesionalnipreklady.cz/?utm_source=direct&utm_campaign=prekladacreklama" target="_blank" class="gad_link"></a></div></div>'; 
	
if (i==2) text='<div class="row reklama1"><div class="gad"><p class="h1_text"><a href="https://www.smartlationpro.com/?affiliate=prekladac&utm_source=peter&utm_campaign=prekladacreklama" target="_blank" title="Profesionální překladatel pro vaši agenturu">Profesionální překladatel pro vaši agenturu</a></p><p class="p_text"><a href="https://www.smartlationpro.com/?affiliate=prekladac&utm_source=peter&utm_campaign=prekladacreklama" target="_blank" title="Profesionální překladatel pro vaši agenturu"><img src="/img/5medium.jpg" class="imgreklama1 floatleft"></a><a href="https://www.smartlationpro.com/?affiliate=prekladac&utm_source=peter&utm_campaign=prekladacreklama" target="_blank" title="Profesionální překladatelé - Marketplace - překladatelské služby 24/7  &amp;  | Smartlationpro.com | To není překladatelská agentura, to je obrovská databáze profesionálních překladatelů">Profesionální překladatelé - Marketplace - překladatelské služby 24/7 | Smartlationpro.com | To není překladatelská agentura, to je obrovská databáze profesionálních překladatelů</a></p><p class="link_text"><a href="https://www.smartlationpro.com/?affiliate=prekladac&utm_source=peter&utm_campaign=prekladacreklama" target="_blank" title="Smartlationpro">www.smartlationpro.com</a></p><a href="https://www.smartlationpro.com/?affiliate=prekladac&utm_source=peter&utm_campaign=prekladacreklama" target="_blank" class="gad_link"></a></div></div>'; 
	
if (i==3) text='<div class="row reklama1"><div class="gad"><p class="h1_text"><a href="https://www.smartlationpro.com/translators/?utm_source=direct&utm_campaign=prekladacreklama" target="_blank" title="Práce pro překladatele">Práce pro překladatele</a></p><p class="p_text"><a href="https://www.smartlationpro.com/translators/?utm_source=direct&utm_campaign=prekladacreklama" target="_blank" title="Práce pro překladatele"><img src="/img/6medium.jpg" class="imgreklama1 floatleft" alt="Práce pro překladatele"></a><a href="https://www.smartlationpro.com/translators/?utm_source=direct&utm_campaign=prekladacreklama" target="_blank" title="Marketplace- 24/7 Registrace překladatele | Smartlationpro.com | Spojujeme překladatele a zákazníky celého světa">Marketplace- 24/7 Registrace překladatele | Smartlationpro.com | Spojujeme překladatele a zákazníky celého světa</a></p><p class="link_text"><a href="https://www.smartlationpro.com/translators/?utm_source=direct&utm_campaign=prekladacreklama" target="_blank" title="Smartlationpro">www.smartlationpro.com</a></p><a href="https://www.smartlationpro.com/translators/?utm_source=direct&utm_campaign=prekladacreklama" target="_blank" class="gad_link"></a></div></div>'; 
	
if (i==4) text='<div class="row reklama1"><div class="gad"><p class="h1_text"><a href="https://www.smartlation.com/?utm_source=direct&utm_campaign=prekladacreklama" target="_blank" title="Smartlation">For a professional Translation</a></p><p class="p_text"><a href="https://www.smartlation.com/?utm_source=direct&utm_campaign=prekladacreklama" target="_blank" title="Smartlation"><img src="/img/translate.jpg" class="imgreklama1 floatleft" alt="For a professional Translation"></a><a href="https://www.smartlation.com/?utm_source=direct&utm_campaign=prekladacreklama" target="_blank" title="Professional Translation Services 24/7  Marketplace-  Translate  Documents &amp; More - Certified Translations | Smartlation.com | More than a Translation Agency">Professional Translation Services 24/7  Marketplace-  Translate  Documents &amp; More - Certified Translations | Smartlation.com | More than a Translation Agency</a></p><p class="link_text"><a href="https://www.smartlation.com/?utm_source=direct&utm_campaign=prekladacreklama" target="_blank" title="Smartlation">www.smartlation.com</a></p><a href="https://www.smartlation.com/?utm_source=direct&utm_campaign=prekladacreklama" target="_blank" class="gad_link"></a></div></div>';

var vse = '<section id="reklamapopup" title="Reklama" class="margin5 anton">' + text + '<br><span onclick="zobrazreklamupopup();" class="glyphicon pointerrefresh24 w3-right" title="Refresh">&#xe031;</span></section>'; 

document.getElementById('adspopup').innerHTML = vse;
} 

zobrazreklamupopup(); 
setInterval("zobrazreklamupopup();",5000);